version: '3.9'
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    container_name: cassandra-chapters
    volumes:
      -  D:/projects/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-chapters
